version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'host'
    environment:
      TZ: 'Europe/Brussels'
      WEBPASSWORD: '4H0L31NMYP1'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
